export const dataProducts = [
  {
    image: "/img/products/1.jpg",
    noProduct: 1,
    title: "Coffee Been",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus, et id officiis quasi illo fuga praesentium beatae voluptate tempora quidem!",
    starNumber: 3,
    discPrice: "30",
    realPrice: "55",
  },
  {
    image: "/img/products/2.jpg",
    noProduct: 2,
    title: "Coffee Cup",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus, et id officiis quasi illo fuga praesentium beatae voluptate tempora quidem!",
    starNumber: 4,
    discPrice: "18",
    realPrice: "30",
  },
  {
    image: "/img/products/3.jpg",
    noProduct: 3,
    title: "Croissant",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus, et id officiis quasi illo fuga praesentium beatae voluptate tempora quidem!",
    starNumber: 4,
    discPrice: "22",
    realPrice: "25",
  },
  {
    image: "/img/products/4.jpg",
    noProduct: 4,
    title: "Brownie",
    desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus, et id officiis quasi illo fuga praesentium beatae voluptate tempora quidem!",
    starNumber: 5,
    discPrice: "25",
    realPrice: "40",
  },
];
